### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by SchmJohan** [cloudspannerecosystem/harbourbridge#111]
## Expected Behavior
Running Harbourbridge on full Postgres database dump including objects such as uniqe indexes and user defined functions.
No expected Errors when executing since it is a plain text sql dump.

## Actual Behavior

Running into an error, i think when encountering **"))"**.

The following Error is raised:

```
Using driver (source DB): pg_dump
Generating schema: 61%panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf8e55c]

goroutine 1 [running]:
github.com/cloudspannerecosystem/harbourbridge/postgres.toIndexKeys(0xc00007e740, 0x3, 0x4, 0x1d, 0xc000436ef8, 0x1)
        /home/<user>/gopath/pkg/mod/github.com/cloudspannerecosystem/harbourbridge@v0.0.0-20210201074528-83765d9da751/postgres/pgdump.go:670 +0x13c
github.com/cloudspannerecosystem/harbourbridge/postgres.processIndexStmt(0xc000501e40, 0xc0003e8cb0, 0xc000548ed0, 0xc0003e8d50, 0x0, 0xc00007e740, 0x3, 0x4, 0x0, 0x0, ...)
        /home/<user>/gopath/pkg/mod/github.com/cloudspannerecosystem/harbourbridge@v0.0.0-20210201074528-83765d9da751/postgres/pgdump.go:213 +0x2e6
github.com/cloudspannerecosystem/harbourbridge/postgres.processStatements(0xc000501e40, 0xc0003e9030, 0x1, 0x1, 0xbf)
        /home/<user>/gopath/pkg/mod/github.com/cloudspannerecosystem/harbourbridge@v0.0.0-20210201074528-83765d9da751/postgres/pgdump.go:190 +0x59b
github.com/cloudspannerecosystem/harbourbridge/postgres.ProcessPgDump(0xc000501e40, 0xc000643ad0, 0x1235b01, 0xc0005bf9e8)
        /home/<user>/gopath/pkg/mod/github.com/cloudspannerecosystem/harbourbridge@v0.0.0-20210201074528-83765d9da751/postgres/pgdump.go:58 +0xb3
main.ProcessDump(0x1281dfb, 0x7, 0xc000501e40, 0xc0005bfad0, 0xc000092810, 0x2)
        /home/<user>/gopath/pkg/mod/github.com/cloudspannerecosystem/harbourbridge@v0.0.0-20210201074528-83765d9da751/main.go:941 +0xe9
main.schemaFromDump(0x1281dfb, 0x7, 0xc000643f28, 0x7fef244896e0, 0x0, 0x414050)
        /home/<user>/gopath/pkg/mod/github.com/cloudspannerecosystem/harbourbridge@v0.0.0-20210201074528-83765d9da751/main.go:432 +0x445
main.schemaConv(0x1281dfb, 0x7, 0xc0005bff28, 0x1d, 0x7fef24480108, 0xc000040780)
        /home/<user>/gopath/pkg/mod/github.com/cloudspannerecosystem/harbourbridge@v0.0.0-20210201074528-83765d9da751/main.go:239 +0x156
main.toSpanner(0x1281dfb, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc000040760, 0x1c, 0xc000643f28, 0xc000040780, ...)
        /home/<user>/gopath/pkg/mod/github.com/cloudspannerecosystem/harbourbridge@v0.0.0-20210201074528-83765d9da751/main.go:184 +0xc05
main.main()
        /home/<user>/gopath/pkg/mod/github.com/cloudspannerecosystem/harbourbridge@v0.0.0-20210201074528-83765d9da751/main.go:167 +0x3f4
```

### 1. Create a sql dump file including the following Line

```sql
CREATE UNIQUE INDEX some_index ON some_schema.some_table USING btree (some_column1, some_column2, some_schema.some_plsql_function(some_column3, some_column4));
```
### 2. Run Harbourbridge
```bash
harbourbridge -schema-only < some_dump.pg_dump
```

## Specifications

- Version: 
  - go version go1.15.7 linux/amd64
  - harbourbridge version from master
- Platform: Windows 10 / GCP Cloud Shell

**Comment by nevinheintze** [comment]
Thanks Johannes for the detailed report and sample dump file.

I've tried to reproduce it but haven't been able to.
The only difference I can see between your setup and mine is the the go version.
I'm using:

  go version devel +c8bd8010ff linux/amd64

Let me try to get access to go1.15.7 (I think cloud shell should do it).
Current thinking is that maybe this is a go issue that's been recently fixed.
Will update again shortly.

**Comment by nevinheintze** [comment]
I'm still not able to reproduce the crash.
Here's what I've run.

I'm running on cloud shell.
go version returns
```
go version go1.15.7 linux/amd64
```
which is the same as yours.

I then ran:
```
GO111MODULE=on go get github.com/cloudspannerecosystem/harbourbridge
```
and:
```
gopath/bin/harbourbridge -schema-only < crash.dump
```
where crash.dump consists of the single line from your report:
```
cat crash.dump
CREATE UNIQUE INDEX some_index ON some_schema.some_table USING btree (some_column1, some_column2, some_schema.some_plsql_function(some_column3, some_column4));
```

I get the following output:

```
gopath/bin/harbourbridge -schema-only < crash.dump
Using driver (source DB): pg_dump
Generating schema: 100%
Wrote schema to file 'pg_dump_2021-02-17_5495-b3b3.schema.txt'.
Wrote session to file 'pg_dump_2021-02-17_5495-b3b3.session.json'.
Processed 161 bytes of pg_dump data (1 statements, 0 rows of data, 0 errors, 1 unexpected conditions).
Schema conversion: NONE (no schema found).
See file 'pg_dump_2021-02-17_5495-b3b3.report.txt' for details of the schema and data conversions.
```

and no crash (the unexpected condition is that table some_schema.some_table can't be found, which is appropriate).

I also tried cloning github and running from the cloned repository:
```
$ git clone https://github.com/cloudspannerecosystem/harbourbridge
Cloning into 'harbourbridge'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 656 (delta 7), reused 7 (delta 1), pack-reused 629
Receiving objects: 100% (656/656), 512.44 KiB | 579.00 KiB/s, done.
Resolving deltas: 100% (436/436), done.
$ cd harbourbridge
$ go run github.com/cloudspannerecosystem/harbourbridge -schema-only < ../crash.dump
Using driver (source DB): pg_dump
Generating schema: 100%
Wrote schema to file 'pg_dump_2021-02-17_dc5c-c3ea.schema.txt'.
Wrote session to file 'pg_dump_2021-02-17_dc5c-c3ea.session.json'.
Processed 161 bytes of pg_dump data (1 statements, 0 rows of data, 0 errors, 1 unexpected conditions).
Schema conversion: NONE (no schema found).
See file 'pg_dump_2021-02-17_dc5c-c3ea.report.txt' for details of the schema and data conversions.
```

Any thoughts on what I'm missing?

**Comment by agasheesh** [comment]
Hi Johannes, we were finally able to reproduce this issue and it turned out to be an issue with an older version of pg_query_go library that HarbourBridge uses to parse pg_dump files. I have sent out a fix in https://github.com/cloudspannerecosystem/harbourbridge/pull/172. Please do reach out in case you run into any future issues.
